- name: Capture Token
  set_fact: b_token={{lookup('env','CLC_V2_API_TOKEN')}}
- name: Override Captured Token
  set_fact:
    b_token: "{{test_b_token}}"
  when: test_b_token is defined

- setup:

- name: register product
  delegate_to: 127.0.0.1
  ignore_errors: yes
  uri:
    url: http://onramp-staging.ctl.io/api/PlatformSubscriptions
    HEADER_Content-Type: "application/json"
    method: POST
    body: '{
      "providerAlias": "{{ providerAlias }}",
      "productId": "{{ productId }}",
      "name": "{{ name }}",
      "bearerToken": "{{ b_token }}",
      "startTime": "{{ start_time }}",
      "endTime": "{{ ansible_date_time.iso8601_micro }}",
      "success": {{ i_success|lower }},
      "errorMessage": "{{ i_message }}",
      "dataCenter": "{{ clc_datacenter }}",
      "servers": {{ groups.all }},
      "executionId": "{{ rnr_execution_id }}"
    }'
    body_format: json
    status_code: 200, 201
    return_content: yes
  register: reg_out

- name: Registration Results
  debug: var=reg_out
