- block:
    - name: install product
      shell: uname -a
      register: ip_out

    - name: output
      debug: var=ip_out

    - name: set status to a tmp val
      set_fact:
        i_success: true
  rescue:
    - set_fact:
        i_success: false
    - set_fact: i_message="installation failed"
